name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    BACKEND_HOST: kubeclarity-kubeclarity.kubeclarity.svc.cluster.local:8080
    BACKEND_DISABLE_TLS: true
    KUBECLARITY_APP_ID: b58c58a9-b8ab-5b7f-ba69-e897034f9251

jobs:
  buildimage:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/schultyy/kubeclarity-ci
          tags: type=sha
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Install KubeClarity
        run: |
          curl -LO https://github.com/openclarity/kubeclarity/releases/download/v2.19.0/kubeclarity-cli-2.19.0-linux-amd64.tar.gz && tar -xzvf kubeclarity-cli-2.19.0-linux-amd64.tar.gz
          sudo mv kubeclarity-cli /usr/local/bin/kubeclarity-cli
      - name: Scan the image
        run: kubeclarity-cli scan ${{ steps.meta.outputs.tags }} --cis-docker-benchmark-scan --application-id $KUBECLARITY_APP_ID -e
