name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Install Toolchain
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Build
      run: $HOME/.cargo/bin/cargo build --verbose
    - name: Run tests
      run: $HOME/.cargo/bin/cargo test --verbose
